.github/workflows/deploy.yml, netlify.toml, package.json, yarn.lock
To make both Netlify & GitHub Actions builds consistent
=> Install Netlify Plugins manually

pages/index.tsx, styles/globals.css
https://web.dev/optimize-cls/#modern-best-practice
=> Fix image aspect ratio while keeping the height property

netlify.toml, package.json, yarn.lock
Self explanatory, this PR adds lighthouse integration for Netlify.
=> Add netlify lighthouse plugin

.gitignore, netlify.toml, pages/index.tsx
Closes #26
Closes #27
Closes #29
=> Resolve SEO issues from the codebase

_content/home-page.md
=> Homepage contents migration

etc/fetchers/fetch-faq-sheet.js, etc/fetchers/fetch-faq-sheets.js, etc/fetchers/fetch-wbw.js
closes #65
Implement sheets fetcher to fetch FAQ database from https://kcov.id/wbw-faq
The fetched content will be stored in data/wbw-faq-sheets.json with the following structure:
```
[
// based on column in the spreadsheet
{
"kategori_pertanyaan": "Tatalaksana Isoman",
"pertanyaan": "Berapa lama isolasi mandiri?",
"jawaban": "TANPA GEJALA: 10 hari pasca hasil tes nya keluar.DENGAN GEJALA: 10 hari dari hari pertama muncul gejala, dan 3 hari terakhir harus bebas gejala. Jika gejala lebih dari 10 hari, isolasi dilanjutkan hingga gejala hilang ditambah dengan 3 hari bebas gejala. ",
"created_date": "10 Jul 2021",
"sumber": "Protokol Tata Laksana COVID-19, Buku Saku Ed. 2",
"link": "https://covid19.go.id/p/protokol/protokol-tatalaksana-covid-19-di-indonesia",
"published_date": "08 Feb 2021" …
```
=> Implement FAQ sheets fetcher

pages/_app.tsx, pages/_document.tsx, pages/index.tsx
So that it exists on all new pages that we're about to create for #17, #31, & #64.
The implementation is inspired by #19.
=> Extract meta tags into Custom `App` & `Document`

.stylelintrc, netlify.toml, package.json, styles/globals.css, yarn.lock
Closes #69
https://stackoverflow.com/a/48165524/3187014
=> Configure stylelint to lint the CSS files

package.json, yarn.lock
For integrating Tailwind CSS with React easily
Closes #72
=> Install @headlessui/react & @heroicons/react

pages/index.tsx
=> Replace getInitialProps with getStaticProps

etc/fetchers/fetch-sheets.js
=> Fix fetch-sheets implementation

README.md
User should run `yarn fetch-wbw` before running development server
=> Clearer setup steps for new contributor

lib/faq-databases.ts, netlify.toml, pages/faqs.tsx, tailwind.config.js
Closes #66 
- [Create faqs ] 
- [ Implement searchable FAQ page based on the fetched FAQ data]
=> create faqs page

next.config.js
As requested by @nibraswastaken.
=> remove experimental scroll restoration

pages/faq.tsx
Forgot to add the page header on FAQ page.
=> add page header on FAQ page

components/contact-list.tsx, lib/string-utils.ts
Fix a bug where all contacts are verified regardless of the `tanggal_verifikasi` field existence
=> Fix isNotEmpty logic and extract it into string-utils.ts

components/layout/global-header.tsx, pages/index.tsx
Minor tweak to padding in home page.
=> fixed padding in home page

components/contact-details.tsx
We need more time to integrate the `ReportButton` with the Google Forms
=> Hide the `ReportButton` component temporarily

components/contact-details.tsx, components/contact-list.tsx, lib/provinces.ts
Update the fields to adjust with the latest schema on the Google Sheets
=> Refactor `tanggal_verifikasi` into `terakhir_update`

netlify.toml
Update `netlify.toml` configuration
- ~Change the `path` to `/home-page` temporarily~
=> Update Netlify Plugin Lighthouse configuration

public/admin/config.yml, public/admin/index.html
Configure Netlify CMS for easier navigation
https://www.netlifycms.org/docs/configuration-options/#site-url
=> Add `site_url` & `display_url` for easier navigation

pages/_app.tsx, pages/index.tsx
Minor fix SEO tags in homepage
=> minor fixes to homepage SEO tags

components/search-form.tsx, components/ui/button.tsx, package.json, yarn.lock
Refactor the button components in search components to `ui/button.tsx`.
=> make button components reusable

package.json, yarn.lock
Upgrades `@netlify/plugin-nextjs` to the latest version.
=> upgrade `@netlify/plugin-nextjs`

components/search-form.tsx, components/ui/select.tsx
Makes select component reusable.
=> make `<select>` component reusable

.github/workflows/test.yml, package.json, yarn.lock
Closes #192, closes #182.
Adds a GitHub Actions workflow with initial steps to run ESLint + TypeScript type checking.
=> add GitHub Actions with ESLint and TypeScript

_content/home-page.md, env.d.ts, pages/home-page.tsx, public/admin/config.yml, tailwind.config.js
=> Prepare the `/home-page` page styling to replace the `/index` page

pages/_app.tsx, pages/home-page.tsx, pages/index.tsx, pages/provinces/[provinceSlug]/[contactSlug].tsx, pages/provinces/[provinceSlug]/index.tsx
Closes #233 
Move "Warga Bantu Warga" to the end of the page title
- **Google Search Preview**
- **Homepage**
- **Province list page**
- **Province detail page**
- **Contact detail page**
=> Move "Warga Bantu Warga" to the end of the page title

components/search-form.tsx, components/ui/forms/form-label.tsx, components/ui/forms/input-checkbox.tsx, components/ui/forms/input-select.tsx, components/ui/forms/input-text.tsx, components/ui/forms/input-textarea.tsx, package.json, tailwind.config.js, yarn.lock
Closes #213 
Compile all form styles into a unified design system.
=> design system - forms + input

lib/htmr-transformers.tsx, lib/string-utils.ts, pages/home-page.tsx
=> Implement headings transformers

pages/provinces/[provinceSlug]/[contactSlug].tsx
Closes #293
Add location, if available
=> feat: title improvement

components/layout/navigation.tsx, lib/layout/navigation-data.tsx
Move the bottom navigation items list from inside the component to `~/lib/layout`.
=> refactor bottom navigation data to `~/lib/layout`

styles/globals.css
Closes #298 
Use css to add pseudo element and position it above the actual element with `id` attribute
=> Fix same-page anchor reference is hidden behind the header

netlify.toml, pages/home-page.tsx, pages/index.tsx, public/admin/config.yml
=> Swap the `index.tsx` with the `home-page.tsx` file

CONTRIBUTING.md
Closes #102 
I'm using a reference from [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) contribution document. Basically, I create tables that list the issues and pull requests labels. I also provide links to the issues page for each label for easier issue access.
Weird spacing format due to prettier I guess 🤔
=> update contributing.md with the issues label documentation

__tests__/pages/faq.test.tsx, components/__tests__/report-button.test.tsx, jest.config.js, lib/__mocks__/builders/faq.ts, lib/__mocks__/builders/provinces.ts, lib/faqs.ts, pages/__tests__/faq.test.tsx, pages/faq.tsx, test/jest.client.js
=> Test `FAQ` page

public/admin/config.yml
=> Make image field not required

components/__tests__/report-button.test.tsx, components/__tests__/search-form.test.tsx, components/ui/__tests__/button.test.tsx, components/ui/button/primary-button.tsx, components/ui/button/secondary-button.tsx, components/ui/button/utils/helpers.ts, components/ui/button/utils/types.ts
Closes #396
Added colour variants to primary + secondary buttons.
=> add color variants to primary + secondary button

README.md
Closes #375
Add badges on readme
=> chore: add badges, codecov and actions

.github/workflows/lighthouse-ci.yml
Fix bug always triggerred on PR that have any labels
**Adding "poc" label**
=> fix: label checking

lib/__tests__/date-utils.test.ts, lib/__tests__/jsonld-generator.test.ts, lib/__tests__/meta.test.ts, lib/__tests__/string-utils.test.ts, lib/date-utils.ts, lib/meta.ts
=> test: add testing on lib

lib/provinces.ts, pages/provinces/[provinceSlug]/[contactSlug].tsx
=> fix: adapt the province slug management in the Contact page

components/search-filter.tsx, components/ui/skeleton-loading.tsx
Tweaks to the search + filter skeleton to make the design fit.
=> refactor: clean up search+filter skeleton

components/home/__tests__/homepage-start.test.tsx, components/home/homepage-start.tsx
Closes #449
Update sembako CTA image to the latest version.
=> feat: update sembako CTA image

.prettierignore, __tests__/pages/faq.test.tsx, __tests__/pages/provinces/[provinceSlug]/index.test.tsx, components/search-form.tsx, jest.config.js, lib/__mocks__/builders/provinces.ts, pages/provinces/[provinceSlug]/index.tsx
=> Test `Provinces` & `Province` page

__tests__/pages/provinces/index.test.tsx
=> Test the search functionality in `ProvincePage`

components/layout/__tests__/global-header.test.tsx, components/layout/__tests__/navigation.test.tsx, test/jest.client.js
Use proper folder structure for tests in Layout components.
=> test: refactor tests folder for layout components

components/ui/skeleton-loading.tsx, pages/faq.tsx
=> Loading & Empty State in FAQ page

.github/workflows/test.yml, package.json
=> refactor: revert back `fetch-wbw` to `mirror-box`

components/__tests__/report-button.test.tsx, components/__tests__/search-form.test.tsx, components/home/__tests__/homepage-start.test.tsx, components/ui/__tests__/button.test.tsx, components/ui/button/ghosted-anchor-button.tsx, components/ui/button/ghosted-button.tsx, components/ui/button/outline-anchor-button.tsx, components/ui/button/outline-button.tsx, components/ui/button/primary-anchor-button.tsx, components/ui/button/primary-button.tsx, components/ui/button/secondary-anchor-button.tsx, components/ui/button/secondary-button.tsx, components/ui/button/utils/__tests__/helpers.test.ts, components/ui/button/utils/helpers.ts, components/ui/button/utils/types.ts, components/ui/button/white-anchor-button.tsx, components/ui/button/white-button.tsx
Closes #480
Add an `iconPosition` prop to button which defaults to `"left"`
=> feat(ui): add `iconPosition` prop to button

.kodiak.toml
=> feat: add Kodiak configuration file

components/home/__tests__/homepage-contributing.test.tsx, components/home/homepage-contributing.tsx, components/home/homepage-section.tsx, components/home/homepage-start.tsx, lib/home/contributing-links.tsx, pages/index.tsx
Closes #323
Added Cara Berkontribusi widget on homepage.
=> feat(ui): homepage contributing widget

components/home/__tests__/homepage-section.test.tsx, components/layout/__tests__/global-header.test.tsx, components/layout/__tests__/navigation.test.tsx, components/layout/global-header.tsx, components/layout/navigation.tsx, components/ui/badge/__tests__/badge.test.tsx, components/ui/badge/utils/types.ts
Closes #498 
Moves the mobile navigation menu to the correct position.
=> fix: move mobile navigation to the top

lib/htmr-transformers.tsx
Closes 
#44 
Add `rel="nofollow"` attribute to all external links
=> fix: add `rel="nofollow"` attribute

components/home/__tests__/homepage-start.test.tsx, components/home/homepage-start.tsx, constants/index.ts
=> refactor: move the sembako URL into a HOMEPAGE_START_CTA_URL constant

_content/site-config.json, components/home/homepage-whatsapp-cta.tsx, components/layout/__tests__/navigation.test.tsx, lib/__mocks__/config.ts, lib/__mocks__/site-config.ts, lib/config.ts, lib/layout/navigation-data.tsx, lib/site-config.ts, pages/_app.tsx, pages/home-page.tsx, pages/index.tsx, pages/isolasi-mandiri.tsx, public/admin/config.yml
Closes #510
Fixes the WhatsApp hotline URL in the navigation bar, as well as adding it to the Netlify CMS site config section so content writers can edit it.
=> feat: add WA hotline URL in config and update all links that use it

components/home/homepage-latest-news.tsx, lib/home/latest-news.ts
Closes #521
Changed text size for latest news content to `text-sm`.
=> fix(ui): fixed text size in latest news section

README.md
Fix "TThe" typos and add missing verb "is spread"
=> docs: fix typos and improve grammar

etc/fetchers/__tests__/utils.test.ts, etc/fetchers/fetch-faq-sheets.ts, etc/fetchers/utils.ts
=> test: fetcher faqs

lib/layout/navigation-data.tsx
Add the Kontak Darurat page to the top navigation menu.
=> feat: add Kontak Darurat page to navigation menu

__tests__/pages/kontak-darurat.test.tsx, components/kontak-darurat/emergency-contact-section.tsx, components/layout/page-content.tsx, components/layout/page-header.tsx, pages/kontak-darurat.tsx
- Improve structure + add page description to Kontak Darurat page
- Minor layout improvements for Page components
=> refactor(layout): minor Page component fixes

components/home/__tests__/homepage-contributing.test.tsx, components/home/__tests__/homepage-whatsapp-cta.test.tsx, components/home/homepage-contributing.tsx, components/home/homepage-latest-news.tsx, components/home/homepage-whatsapp-cta.tsx, components/ui/__tests__/button.test.tsx, components/ui/button/__tests__/outline-anchor-button.test.tsx
Closes #572 
Improve text color contrast to improve accessibility
<details>
<summary>Detailed changes (click to expand)</summary>
---
**"Informasi Terbaru" dates**
- Before
- After
---
**"Informasi Terbaru" CTA**
- Before
- After
---
**"Tambahkan info" CTA**
- Before
- After
---
**Whatsapp contact CTA**
- Before
- After
</detail>
=> fix: improve text color contrast

components/__tests__/contact-list-item.test.tsx, components/contact-list-item.tsx, lib/data/__mocks__/builders/provinces.ts
Closes #570 
Add copy button in province list
=> feat(ui): open map button in list

components/home/__tests__/homepage-start.test.tsx, components/home/homepage-start.tsx
Closes #573 
Change copywriting from Cek sekarang to Telusuri sekarang in homepage-start and its corresponding test file.
- Change copywriting from Cek sekarang to Telusuri sekarang in homepage-start
- Change copywriting from Cek sekarang to Telusuri sekarang in homepage-start.test
=> change copywriting from Cek sekarang to Telusuri sekarang

components/home/__tests__/homepage-whatsapp-cta.test.tsx
Closes #509 
Adding test assertion when rendering HomePageWhatsAppCTA
I think we can add more issues to cover multiple components @zainfathoni, so we can add more specific tests on specific components. This Implementation only covers href. 
Do you have any guidance for me on what kind of assertions / best practices we need check-in component?
Eager learn from Wargabantuwarga team.
=> test: add href test assertion

CONTRIBUTING_ID.md
Add a space between text and screenshots on 'Langkah-langkah untuk membuat _Draft Pull Request_'
=> docs(id): add space between text and screenshots

README.md
- Explicitly state that we use yarn, not npm.
- Explicitly state that English language is required.
=> docs: update README to add more requirements

netlify.toml, next.config.js
Closes #608
Closes #609
Adds the following headers across all resources:
- `X-Content-Type-Options: nosniff` to prevent content type sniffing
- `X-Frame-Options: DENY` to prevent clickjacking
=> chore(security): add essential security headers

components/kontak-darurat/__tests__/chatbot-section.test.tsx, components/kontak-darurat/chatbot-section.tsx, components/kontak-darurat/emergency-contact-section.tsx
Partial work for #624 
Enlarged the heading text on these sections:
=> style: minor tweaks to emergency contact layout

__tests__/pages/tentang-kami.test.tsx, constants/image.ts, lib/__tests__/cloudinary-utils.test.ts, lib/image/cloudinary-utils.ts, pages/tentang-kami.tsx
Continue #616 
Setup Next/Image for `/tentang-kami`
=> feat(image): using next/image

netlify.toml
Closes #651 
seperate csp header for admin page
=> fix: seperate csp for admin page

components/home/__tests__/homepage-start.test.tsx, components/home/homepage-menu.tsx, lib/home/homepage-menus.tsx
Closes #654
handle external URL to open it on the new tab with proper rel attribute value
=> feat: handle external url icon

_content/about/collaborators.json
Closes #627
Automatically generated by Netlify CMS
=> Update About Page “collaborators_about_page”

_content/home-page.md
Closes #672 
Automatically generated by Netlify CMS
=> Update Home Page “home_page”

components/donasi/donation-card.tsx, components/kontak-darurat/emergency-contact-card.tsx, components/telemedicine/telemedicine-contact-card.tsx
Minor text size adjustments for cards across the site.
=> style: adjust text size on cards

components/home/__tests__/homepage-start.test.tsx, lib/home/homepage-menus.tsx, lib/layout/navigation-data.tsx
Closes #674
Add entry point to `/edukasi` in homepage and navigation
=> feat: edukasi entry point

_content/donasi.json
Help #698
Automatically generated by Netlify CMS
=> Update Donasi Page “informasi_donasi”

components/donasi/donation-card.tsx
Closes #666 
Replace color button with primary button.
=> fix: color contrast ratio of Donasi Sekarang button

netlify.toml, next.config.js
=> fix: try adding res.cloudinary.com to the content security policy header

next-env.d.ts, next.config.js
=> fix: try reverting `next-pwa` usage to fix #716

.gitignore, public/service-worker.js
Closes #716
This is my attempt to fix the stale service worker issue installed at #705, CMIIW @resir014 @mazipan.
=> fix: add self-destroying service worker

CONTRIBUTING.md, CONTRIBUTING_ID.md
Closes #318 
Update **`Start working on Issues`** section with clearer instructions on getting ready to work on an issue.
=> docs: explain forking mechanism to CONTRIBUTING

netlify.toml
...I really shouldn't make pull requests the first thing in the morning.
=> fix: add CSP header for analytics in the correct paths

.github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml, .github/workflows/lighthouse-ci-prod.yml, .github/workflows/test.yml
Closes #740 
We only need to run GitHub action on Upstream not on forked repo you can check my forked repo and PR
- https://github.com/rubiagatra/wargabantuwarga.com/actions
- https://github.com/rubiagatra/wargabantuwarga.com/pull/1
If on upstream still run the actions, we are good
=> refactor: update GitHub action for not running on forked repo

README.md
Closes #751
Add the Cypress logo as our supporter.
=> docs: add Cypress logo as supporter

README.md
Closes #754
Add the Netlify logo to our list of supporters.
=> docs: add Netlify logo to our supporters list

components/donasi/donation-card.tsx
Closes #764 
This pull request fixes unnecessary image rounding by replacing `rounded-md` with `rounded-t-md` in `DonationCard` component.
=> fix: replace rounded-md with rounded-t-md

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature-request.md
to make it consistent with kawalcovid19/silacak repository
=> docs(template): remove default assignees from issue templates

constants/report.ts, pages/faq.tsx
Closes #83
I created a small clickable link for reporting wrong answers.
Sorry for the long delay, I was busy in the past week.
=> feat: add reporting link with prefill

_content/home-page.md, components/home/__tests__/homepage-supported-apps.test.tsx, components/home/homepage-supported-apps.tsx, pages/index.tsx, public/admin/config.yml
I didn't read issue #712 correctly. Since PR #722 already merged and the issue was automatically closed, I made a few changes to complete all tasks that still remain.
Closes #722 
Before:
After:
=> feat: add Telekonseling Page to CMS & update Homepage

components/contact-list-item.tsx
=> fix: put back the mistakenly removed kebutuhan badge

pages/lbh/index.tsx
=> feat: update copywriting to optimize for discoverability
