.stylelintrc
pages/index.tsx
styles/globals.css

First iteration of #68, not really resolve as this is only minor style adjustment
Feedback from my wife, when visiting through mobile feels cramped.
My solution was to:
1. Set the width to 40 rem on larger screen devices, but take full `100vw` on mobile device.
2. Make necessary changes to both article and header image so header image still take 100% of space, while the article have small padding as it contains mostly text
Before/After

minor style adjustment for mobile devices

---

etc/fetchers/fetch-sheets.js

Closes 
The query selector that involves `nth-child` check is very expensive, so we remove it to improve the performance. Based on the data at https://github.com/kawalcovid19/wargabantuwarga.com/discussions/139, it could reduce the duration for sheet fetching from 39.98s to 25.41s.

Remove nth child check for faster performance

---

components/layout/page-content.tsx
components/layout/page.tsx
pages/404.tsx
pages/_error.tsx

a height of 100vh doesn't work well on child containers, causing a rogue scrollbar to appear.
This fixes it.

remove `min-h-screen` class on error pages

---

components/contact-details.tsx
components/contact-list.tsx
etc/fetchers/fetch-sheets.js
lib/htmr-transformers.tsx
lib/provinces.ts
netlify.toml
pages/provinces/[provinceSlug]/index.tsx

Fix missing `Tautan` and render some fields as rich-text content

---

components/layout/global-header.tsx
components/layout/layout-root.tsx
components/layout/navigation.tsx
components/layout/page.tsx
netlify.toml

Closes #122 
Added initial iteration of global footer navigation. Currently only links to Home, Provinces, and FAQ pages. Will probably need to redesign as we add more pages.

added footer navigation

---

components/layout/back-button.tsx
pages/provinces/[provinceSlug]/index.tsx

Rename province slug page title:
Fix copywriting on Back button (mobile only)

minor fixes to some page header titles + back button

---

.gitignore

Some new contributors keep using `npm` even though the project itself uses `yarn`. This PR add `package-lock.json` to the gitignore file so that people won't accidentally commit npm's lockfile to the project.
In the future, we should explicitly mention in the README that **we use yarn, not npm**.

add `package-lock.json` to gitignore

---

package.json
tsconfig.json
yarn.lock

Turns out adding a `ts-node` key to `tsconfig.json` will make `ts-node` load that specific config. We can remove the environment variable setup this way.
Reference: https://github.com/TypeStrong/ts-node/issues/606#issuecomment-670055983

add ts-node compiler options in `tsconfig.json`

---

components/contact-list.tsx
components/province-list.tsx
components/ui/empty-state.tsx

Closes #210. Closes #216.
Add an empty state component and use it in the `ProvincesList` and `ContactList` when data is empty.

add empty state on provinces + contact list

---

components/search-form.tsx

fix: conditional on filter

---

.eslintrc
components/contact-details.tsx
components/contact-list.tsx
components/layout/global-header.tsx
components/layout/navigation.tsx
components/layout/page-header.tsx
components/report-button.tsx
components/script.tsx
components/search-form.tsx
lib/faq-databases.ts
lib/jsonld-generator.ts
lib/provinces.ts
pages/404.tsx
pages/_app.tsx
pages/_error.tsx
pages/faq.tsx
pages/home-page.tsx
pages/index.tsx
pages/provinces/[provinceSlug]/[contactSlug].tsx
pages/provinces/[provinceSlug]/index.tsx
pages/provinces/index.tsx
tsconfig.json

Closes https://github.com/kawalcovid19/wargabantuwarga.com/issues/225
Configure tsconfig.json for module path alias with leading `~` from base URL (`./`).
example: `import { PageContent } from "~/components/layout/page-content";`
Nextjs and eslint use tsconfig, might need to update other utilities such as test runner later when it exists to support the path alias.
ref: https://nextjs.org/docs/advanced-features/module-path-aliases

Absolute imports and module path alias

---

lib/hooks/use-search.ts

Closes #362 
Since itemsjs using lunr.js, `a` is included as stop words and filtered. 
Since our data is in Bahasa Indonesia, this process is unnecessary.
Itemsjs has isExactSearch setting on the configuration to show exact search matches related to this matter. 
Fix vs current 
test case: `a`
test case: `be`
test case: `he`

Fix Province Search Bug on Letter A

---

components/search-form.tsx
pages/provinces/[provinceSlug]/index.tsx

Closes #347
The user may not know that he/she can search by address, provider, description and ofcourse the contact number, then look for it by the contact number only.

Improve province search #347

---

.github/workflows/lighthouse-ci-prod.yml

Action `jakepartusch/wait-for-netlify-action@v1` will failed on `main` branches, we need to split the CI for main and pull-request

fix(ci): netlify preview action error on main

---

components/__tests__/search-form.test.tsx
components/search-filter-modal.tsx
components/search-filter.tsx
components/search-form.tsx
pages/provinces/[provinceSlug]/index.tsx

Closes #417
Just in case modal is still needed later, add `useFilterModal` as setting whether to show filter as modal or not. 
Refactor `renderSearchFilter` in `SearchFilterModal` as new component.
If `useFilterModal` is false, render `SearchFilter` instead `SearchFilterModal`.

Revert filter & sort ui

---

package.json

Closes #412
Revert back to `mirror-box` from `fetch-wbw` due to #361.

fix: Revert back to mirror-box

---

pages/_app.tsx
pages/_document.tsx

Closes issue on #419 
Move GTM under the body

fix(gtm): move noscript under body

---

pages/index.tsx

Closes #464
Removes trailing semicolon at the homepage.

fix: remove trailing semicolon at homepage

---

.github/workflows/test.yml
__tests__/pages/provinces/[provinceSlug]/[contactSlug].test.tsx
etc/fetchers/fetch-sheets.ts
jest.config.js
lib/__mocks__/builders/provinces.ts
lib/__mocks__/provinces.ts
lib/__tests__/provinces.test.ts
lib/__tests__/string-utils.test.ts
lib/province-utils.ts
lib/provinces.ts
lib/string-utils.ts
package.json
pages/provinces/[provinceSlug]/[contactSlug].tsx
pages/provinces/[provinceSlug]/index.tsx

Closes #383
Closes  #289 because it's hard to write the tests without closing it

Implement static slug for `Contact` page and add more tests to verify the changes

---

components/__tests__/search-filter.test.tsx
components/__tests__/search-form.test.tsx
components/ui/forms/input-select.tsx
components/ui/forms/input-text.tsx
components/ui/forms/input-textarea.tsx

On mobile devices, the default input text, select, and textarea font sizes make the form not have the same height as a button with size `md`. This fixes it.

fix(ui): fix incorrect text-size on form components

---

components/contact-details.tsx
components/contact-list-item.tsx
components/home/__tests__/homepage-latest-news.test.tsx
components/home/homepage-latest-news.tsx
lib/home/latest-news.ts
lib/htmr-transformers.tsx
pages/index.tsx

Partial work for #324
Added latest news section implementation. Initially this will use dummy data, no Netlify CMS. But the shape of the interface already fits what was meant to be implemented on the Netlify CMS collection.
Will probably implement Netlify CMS on the same PR. cc: @zainfathoni
Design can already be reviewed. cc: @baraeb92

feat: latest news section implementation

---

pages/faq.tsx

Closes #522 
Adding `mt-2` to `<small>` tag. Seems a very little difference though.
**Before**
**After**

fix(ui): adding little margin

---

components/contact-details.tsx

Closes #344  
Enclose `Buka Peta` button and `Salin` button inside a flex container with flex-wrap on.

Move `Buka Peta` button under `Salin` button

---

components/layout/page-header.tsx

Improve page hierarchy by using `<h1>` for `PageHeader` title.

fix: use `h1` for page headers

---

pages/_app.tsx

WBW now has an official Twitter handle, so we change the Twitter Card's `handle` setting to that.

perf(seo): change Twitter Card handle

---

components/layout/stacked-link.tsx
pages/isolasi-mandiri.tsx

Fixed the SEO title in Isolasi Mandiri page so the site name doesn't get duplicated. (by default the title template set by next-seo is `%s | site_name`)
**Before**
**After**
Improve accessibility on Isolasi Mandiri page + its stacked links by using proper semantic HTML elements instead of `div`.

fix: use correct SEO title + improve a11y on Isolasi Mandiri page

---

components/home/__tests__/homepage-start.test.tsx
constants/index.ts

Closes #548
Reverts the Sembako CTA URL back to `sembako.wargabantuwarga.com`

fix: change sembako URL back to `sembako.wargabantuwarga.com`

---

.kodiak.toml

Allow Kodiak bot to auto-merge dependencies updates from Dependabot without approval. Only minor and patch updates are automatically merged, major deps upgrades still need our manual approval.

chore(kodiak): auto-merge deps updates from dependabot

---

README.md

Closes #632 
Added GitBook as supporter into README.md file. I put it above **Contributing** section. The result is going to look like this:
Special thanks goes to our supporter.
<p align="center"><a href="https://www.gitbook.com/" target="_blank" rel="noopener noreferrer"><img width="300" src="https://user-images.githubusercontent.com/56619123/128886904-5887e9e2-e444-4db5-81f8-5cd33a3d79ad.png" alt="GitBook Logo"></a></p>

docs: add gitbook as supporter

---

netlify.toml
next.config.js

Closes #610
Added a `Permissions-Policy` header to control which features and APIs can be used in the browser.

perf(security): added `Permissions-Policy` header

---

netlify.toml
next.config.js

Closes #611 
Added a `Content-Security-Policy` header to prevent cross-site scripting (XSS).
- defaultSrc : self
- styleSrc : unsafe-inline
- scriptSrc : self, .googletagmanager.com
- imgSrc : self, https:, data: 
for `unsave-eval` on `scriptSrc`, we need to check if it's production or not. 
because in development webpack use unsave-eval.

security: Add Content-Security-Policy

---

package.json

This pull request reverts back to deployment script from `fetch-wbw` to `mirror-box` caused by #606

fix: revert back to mirror box

---

netlify.toml
next.config.js

Closes #651 
add this url, to be allowed in `script-src` CSP
- *.netlify.com 
- unpkg.com 
- analytics.google.com 
- *.google-analytics.com

Fix : allow some url to be allowed in `script-src` CSP

---

etc/fetchers/__tests__/utils.test.ts
etc/fetchers/utils.ts

Closes #613 
Fixed the issue of overflow alamat, root cause of this problem is data alamat from source data have html tag.
note: don't forget to re-run `yarn fetch-wbw` to renew data

fix: overflow alamat

---

components/home/__tests__/homepage-start.test.tsx
components/home/__tests__/homepage-telemedicine-cta.test.tsx
components/home/homepage-start.tsx
components/telemedicine/telemedicine-cta.tsx
pages/tentang-kami.tsx

Our homepage load many non-critical image on initial load. This PR try to solve that problem. Only load above the fold images.

fix: remove non-critical image from initial load

---

__tests__/pages/provinces/index.test.tsx
components/__mocks__/builders/province-list.tsx
components/province-list.tsx
lib/data/helpers/provinces.ts
pages/provinces/index.tsx

Closes #581 
Fixed the issue of Province List displaying the total count of all contacts instead of the contacts of a specific `kebutuhan`. I added new fields in `provinces` props that count only contacts of a specific `kebutuhan`.

fix: display filtered `kebutuhan` contacts count on province-list

---

components/layout/__tests__/navigation.test.tsx
components/layout/navigation-menu.tsx
components/layout/navigation.tsx

Closes #723 
I add some tailwind classes to `NavigationMenuPopover` component and `Navigation` component. Basically, I add `overflow-auto` to make NavigationMenu scrollable and then add `z-40` to make `Navigation` component to front.

fix: make NavigationMenuPopover scrollable and not override Navigation

---

next-env.d.ts
pages/tentang-kami.tsx

Balanced out the logos section in the About Us page, since it's a bit all over the place right now with the `space` helper.
**Before:**
**After**

fix: tweak logos section in the about us page

---

netlify.toml
next.config.js

Another rule that we forgot to add.

fix(security): add CSP rules for `stats.g.doubleclick.net`

---

package.json
tailwind.config.js
yarn.lock

Migrate Tailwind CSS config to use `tailwind-preset-wbw`. Any changes to the Tailwind CSS config shall be made in the presets repo from now on:
https://github.com/kawalcovid19/tailwind-preset-wbw

chore: migrate tailwind config to `tailwind-preset-wbw`

---

components/kontak-darurat/emergency-contact-card.tsx

Fixed the colours for the card buttons from `light-blue` to `brand` to make it consistent with the other pages' cards.
**Before**
**After**

fix: changed card button colours to `brand`

---

.github/workflows/deploy.yml

Closes #246
- Add additional cron schedule (github workflow able to accept multiple schedules as stated in https://github.community/t/multiple-schedules-for-workflow/154811)
- Adjust the hour as the workflow hour is UTC but ours is UTC+7
- For 18 - 22 (01.00 WIB - 05.00 WIB) it runs every 1 hour and for 0 - 17,23 (06.00 WIB - 24.00 WIB) it runs every 30 minutes (note that the cron schedule is inclusive)

Add Conditional Deployment Schedule Based on Hour

---

components/home/homepage-supported-apps.tsx
components/home/homepage-whatsapp-cta.tsx
pages/index.tsx

Fixes the CTA button for the counseling widget to have `block` variant.
Adds extra bottom padding on the WhatsApp widget to make space for the scroll to top button.

fix: minor fixes to homepage widgets

---

etc/fetchers/__mocks__/wbw-database.html
etc/fetchers/__mocks__/wbw-database.json
etc/fetchers/__tests__/fetch-database.test.ts
etc/fetchers/fetch-database.ts
etc/fetchers/fetch-wbw.ts
jest.config.js
package.json
test/jest-common.js
test/jest.server.js
test/setup.server.js
yarn.lock

Closes #784 
Implement `fetch-database.ts` to fetch from https://kcov.id/wbw-database

Feat Implement `fetch-database.ts`

---

etc/mirror-box.ts
jest.config.js

Closes #785 
add fetchDatabase on mirror-box

feat: add fetchDatabase on mirror-box

---

components/contact-list.tsx
cypress/e2e/contacts/search.js
cypress/support/commands.js
package.json
yarn.lock

test(e2e): write more e2e tests for provinces page and its subpages

---

package.json

Revert a7532dd of https://github.com/Nefoplayground/wargabantuwarga.com
That commit was supposedly used only for debugging purposes,
but it was unintentionally merged in #806.
Also see https://github.com/kawalcovid19/wargabantuwarga.com/pull/806#issuecomment-942403579, it's why the commit existed in the first place.
Nothing, but #804 might be required to be merged before this PR? Though, this hasn't been used anywhere else, so it won't really hurt. 🙂

chore: revert fetching data every Netlify export
